#+title: AI Agents Guidance for lcnt.xxx

This file provides guidance to Claude Code (claude.ai/code) when working with code in this repository.

* Table of Contents     :TOC:
- [[#this-repo-contains-lcnts][This Repo contains LCNT's]]
- [[#running-latex-on-inputs][Running LaTeX on Inputs]]
- [[#git-commits-and-git-pushes][Git Commits and Git Pushes]]

* This Repo contains LCNT's

ByStar LCNT (Libre CoNtenT) is a layer on top of LaTeX and HeVeA and Reveal for consistent production of
pdf, html and reveal content.

The scope of types of content spans: memos, articles, books and multimedia presentation.

Read everything under /bisos/panels/bisos-apps/lcnt to understand various aspects of LCNT.


* Running LaTeX on Inputs

After edits to latex files, run:

lcntProc.sh -h -v -n showRun -p pre="clean" -p extent="build" -i lcntBuild cur  # Runs dblock

to produce pdf and other outputs.

* Git Commits and Git Pushes

I don't want Claude to suggest the prompt of "commit this" or "push this".
I want to do all the commits and pushes myself.
Instead just suggest that I can commit.

