#+title: AI Agents Guidance for This Repo

This file provides guidance to Claude Code (claude.ai/code) when working with code in this repository.
It is usually sourced from CLAUDE.md

* Table of Contents     :TOC:
- [[#ai-collaboration-workflow][AI Collaboration Workflow]]
- [[#general-aspects-of-this-repo][General Aspects of This Repo]]
- [[#development-status-and-continuation-of-development][Development Status and Continuation of Development]]
- [[#work-plan][Work Plan]]

* AI Collaboration Workflow

See [[file:./AI-WORKFLOW.org]] for ByStar's (BISOS, Blee) overall AI collaborative development workflow.

@./AI-WORKFLOW.org

* General Aspects of This Repo

See [[file:./AI-Activity.org]] for details.

@./AI-Activity.org

which describes the repo and provides a global overview.


* Development Status and Continuation of Development

Current state of development is at: [[file:./AI-DevStatus.org]]

@./AI-DevStatus.org

* Work Plan

AI collaborative developemnt uses [[file:./AI-WorkPlan.org]]

@./AI-WorkPlan.org

